server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://rm-bp1b74u1bscf7q2ed3o.mysql.rds.aliyuncs.com:3306/cloud_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cloud_root
    password: Root1019
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    # eureka的服务名称
    name: userservice
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      # eureka的地址信息，现在是单机，如果多的话用逗号隔开
      defaultZone: http://127.0.0.1:10086/eureka